export const SKILL_NAME = 'ac-workflow'
export const AC_ROOT_DIR = '.agent-context'
export const PLAN_FILE_NAME = 'plan.md'
export const DONE_DIR = 'done'
export const ENV_FILE_NAME = '.env'
export const PROTOCOL_DIR = 'references'
export const SCRIPTS_DIR = 'scripts'
export const CONTEXT_SCRIPT_NAME = 'get-context-info.mjs'
