name: docs

on:
  # push到main分支时触发
  push:
    branches: [v3.x]

jobs:
  docs:
    # 提交信息中包含docs: 则触发doc构建
    if: contains(github.event.head_commit.message, 'docs:')
    runs-on: ubuntu-latest
    steps:
      - name: 拉取代码
        uses: actions/checkout@v4

      - name: 设置node环境
        uses: actions/setup-node@v4
        with:
          node-version: '20.x'

      - name: node_modules缓存
        uses: actions/cache@v3
        with:
          path: ~/.pnpm-store
          key: ${{ runner.os }}-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-

      # 如果缓存没有命中，安装依赖
      - uses: pnpm/action-setup@v2
        with:
          version: latest

      - name: 安装依赖
        run: pnpm install

      - name: 构建文档
        run: pnpm docs:build

      # 部署
      - name: 部署到线上
        uses: crazy-max/ghaction-github-pages@v4
        with:
          # 部署到 gh-pages 分支
          target_branch: gh-pages
          # 部署目录为 VuePress 的默认输出目录
          build_dir: docs/.vitepress/dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
